# Form implementation generated from reading ui file 'frontend\ui\Classroom\classroom_classworks_content.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_classworkWidget(object):
    def setupUi(self, classworkWidget):
        classworkWidget.setObjectName("classworkWidget")
        classworkWidget.resize(400, 300)
        classworkWidget.setStyleSheet("QWidget {\n"
"    background-color: #F5F5F5;\n"
"    font-family: \"Poppins\";\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(classworkWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mainVerticalLayout = QtWidgets.QVBoxLayout()
        self.mainVerticalLayout.setContentsMargins(15, 15, 15, 15)
        self.mainVerticalLayout.setSpacing(10)
        self.mainVerticalLayout.setObjectName("mainVerticalLayout")
        self.topBarLayout = QtWidgets.QHBoxLayout()
        self.topBarLayout.setSpacing(10)
        self.topBarLayout.setObjectName("topBarLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.topBarLayout.addItem(spacerItem)
        self.createButton = QtWidgets.QPushButton(parent=classworkWidget)
        self.createButton.setMinimumSize(QtCore.QSize(100, 35))
        self.createButton.setMaximumSize(QtCore.QSize(100, 35))
        self.createButton.setStyleSheet("QPushButton {\n"
"    background-color: #084924;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 11px;\n"
"    border-radius: 29.5px;\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #1B5E20;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0D4E12;\n"
"}")
        self.createButton.setObjectName("createButton")
        self.topBarLayout.addWidget(self.createButton)
        self.topicFilterCombo = QtWidgets.QComboBox(parent=classworkWidget)
        self.topicFilterCombo.setMaximumSize(QtCore.QSize(276, 35))
        self.topicFilterCombo.setObjectName("topicFilterCombo")
        self.topicFilterCombo.addItem("")
        self.topicFilterCombo.addItem("")
        self.topicFilterCombo.addItem("")
        self.topBarLayout.addWidget(self.topicFilterCombo)
        self.mainVerticalLayout.addLayout(self.topBarLayout)
        self.verticalLayout_2.addLayout(self.mainVerticalLayout)

        self.retranslateUi(classworkWidget)
        QtCore.QMetaObject.connectSlotsByName(classworkWidget)

    def retranslateUi(self, classworkWidget):
        _translate = QtCore.QCoreApplication.translate
        classworkWidget.setWindowTitle(_translate("classworkWidget", "classroom_classworks_content"))
        self.createButton.setText(_translate("classworkWidget", "Create"))
        self.topicFilterCombo.setItemText(0, _translate("classworkWidget", "All Topics"))
        self.topicFilterCombo.setItemText(1, _translate("classworkWidget", "Material"))
        self.topicFilterCombo.setItemText(2, _translate("classworkWidget", "Assessment"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    classworkWidget = QtWidgets.QWidget()
    ui = Ui_classworkWidget()
    ui.setupUi(classworkWidget)
    classworkWidget.show()
    sys.exit(app.exec())
