# Form implementation generated from reading ui file 'frontend/ui/Classroom/classroom_home.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(787, 435)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.content = QtWidgets.QWidget(parent=Form)
        self.content.setStyleSheet("background-color: #F7F7F7;\n"
"border-radius: 20px;")
        self.content.setObjectName("content")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.content)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.cardFrame = QtWidgets.QFrame(parent=self.content)
        self.cardFrame.setMinimumSize(QtCore.QSize(310, 300))
        self.cardFrame.setMaximumSize(QtCore.QSize(310, 300))
        self.cardFrame.setStyleSheet("background-color: white;\n"
"border-radius: 20px;\n"
"")
        self.cardFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.cardFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.cardFrame.setObjectName("cardFrame")
        self.label = QtWidgets.QLabel(parent=self.cardFrame)
        self.label.setGeometry(QtCore.QRect(10, 10, 291, 151))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("frontend/ui/Classroom\\../../../../img_bookclub.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(parent=self.cardFrame)
        self.label_5.setGeometry(QtCore.QRect(190, 110, 101, 101))
        self.label_5.setStyleSheet("border-radius: 50%;\n"
"background-color: #FDC601;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(parent=self.cardFrame)
        self.label_2.setGeometry(QtCore.QRect(30, 26, 109, 64))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("color: #ffffff;\n"
"font-size: 36px;\n"
"background-color: transparent;\n"
"font-family: \"Poppins\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.cardFrame)
        self.label_4.setGeometry(QtCore.QRect(30, 110, 106, 22))
        self.label_4.setStyleSheet("color: white;\n"
"font-family: \"Poppins\";\n"
"font-size: 12px;\n"
"background-color: transparent;")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(parent=self.cardFrame)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 70, 28))
        self.label_3.setStyleSheet("color: white;\n"
"font-family: \"Poppins\";\n"
"font-size: 16px;\n"
"background-color: transparent;\n"
"")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.cardFrame, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.cardFrame_2 = QtWidgets.QFrame(parent=self.content)
        self.cardFrame_2.setMinimumSize(QtCore.QSize(310, 200))
        self.cardFrame_2.setMaximumSize(QtCore.QSize(310, 300))
        self.cardFrame_2.setStyleSheet("background-color: white;\n"
"border-radius: 20px;\n"
"")
        self.cardFrame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.cardFrame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.cardFrame_2.setObjectName("cardFrame_2")
        self.label_6 = QtWidgets.QLabel(parent=self.cardFrame_2)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 291, 151))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("frontend/ui/Classroom\\../../../../img_bookclub.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.cardFrame_2)
        self.label_7.setGeometry(QtCore.QRect(190, 110, 101, 101))
        self.label_7.setStyleSheet("border-radius: 50%;\n"
"background-color: #FDC601;")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.cardFrame_2)
        self.label_8.setGeometry(QtCore.QRect(30, 26, 121, 64))
        self.label_8.setAutoFillBackground(False)
        self.label_8.setStyleSheet("color: #ffffff;\n"
"font-size: 36px;\n"
"background-color: transparent;\n"
"font-family: \"Poppins\";\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.cardFrame_2)
        self.label_9.setGeometry(QtCore.QRect(30, 110, 121, 22))
        self.label_9.setStyleSheet("color: white;\n"
"font-family: \"Poppins\";\n"
"font-size: 12px;\n"
"background-color: transparent;")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.cardFrame_2)
        self.label_10.setGeometry(QtCore.QRect(30, 80, 70, 28))
        self.label_10.setStyleSheet("color: white;\n"
"font-family: \"Poppins\";\n"
"font-size: 16px;\n"
"background-color: transparent;\n"
"")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.cardFrame_2, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.content)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "home"))
        self.label_2.setText(_translate("Form", "ITSD81"))
        self.label_4.setText(_translate("Form", "Neil John Jomaya"))
        self.label_3.setText(_translate("Form", "BSIT - 3C"))
        self.label_8.setText(_translate("Form", "ITSD83"))
        self.label_9.setText(_translate("Form", "Mindell Rey Aguirre"))
        self.label_10.setText(_translate("Form", "BSIT - 3C"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
